import React, { Fragment } from 'react';
import Head from 'next/head';

import Layout from './../../components/layout';

import styles from './Following.module.scss';

function Following() {
  return (
    <Fragment>
      <Head>
        <title>Đang Follow</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div className={styles.container}>Following page</div>
    </Fragment>
  );
}

export default Following;

Following.Layout = function LayoutPage() {
  return (
    <Layout header={true} sidebar={true}>
      <Following />
    </Layout>
  );
};
