import React, { Fragment } from 'react';
import Head from 'next/head';

import Layout from './../../components/layout';

function Following() {
  return (
    <Fragment>
      <Head>
        <title>Đang Follow</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Following page</div>
    </Fragment>
  );
}

export default Following;

Following.Layout = function LayoutPage() {
  return (
    <Layout header={true} sidebar={true}>
      <Following />
    </Layout>
  );
};
