import { Fragment } from 'react';
import Head from 'next/head';

import styles from './../styles/Home.module.scss';

function Home() {
  return (
    <Fragment>
      <Head>
        <title>Trang chủ</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div>
        <h1>Home page</h1>
      </div>
    </Fragment>
  );
}

export default Home;
