import { Fragment } from 'react';
import Head from 'next/head';

function Home() {
  return (
    <Fragment>
      <Head>
        <title>Trang chủ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Home page</h1>
      </div>
    </Fragment>
  );
}

export default Home;
