import { Fragment } from 'react';
import Head from 'next/head';

import Layout from './../../components/layout';

import styles from './Feedback.module.scss';

function Feedback() {
  return (
    <Fragment>
      <Head>
        <title>Nhận xét</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div className={styles.styles}>Feedback</div>
    </Fragment>
  );
}

export default Feedback;

Feedback.Layout = function LayoutPage() {
  return (
    <Layout header={true} sidebar={false}>
      <Feedback />
    </Layout>
  );
};
