import { Fragment } from 'react';
import Head from 'next/head';

import Layout from './../../components/layout';

function Feedback() {
  return (
    <Fragment>
      <Head>
        <title>Nhận xét</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2>Feedback</h2>
    </Fragment>
  );
}

export default Feedback;

Feedback.Layout = function LayoutPage() {
  return (
    <Layout header={true} sidebar={false}>
      <Feedback />
    </Layout>
  );
};
