import { Fragment } from 'react';
import Head from 'next/head';

import styles from './Live.module.scss';

function Live() {
  return (
    <Fragment>
      <Head>
        <title>Trực tiếp</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div className={styles.container}>Live page</div>
    </Fragment>
  );
}

export default Live;
