import { Fragment } from 'react';
import Head from 'next/head';

function Live() {
  return (
    <Fragment>
      <Head>
        <title>Trực tiếp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Live page</div>
    </Fragment>
  );
}

export default Live;
