import React, { Fragment } from 'react';
import Head from 'next/head';

function Music() {
  return (
    <Fragment>
      <Head>
        <title>Music</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>page Music</div>
    </Fragment>
  );
}

export default Music;
