import { Fragment } from 'react';
import Head from 'next/head';

import Layout from '../../components/layout';

import styles from './Upload.module.scss';

function Upload() {
  return (
    <Fragment>
      <Head>
        <title>Upload</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div className={styles.container}>Upload</div>
    </Fragment>
  );
}

export default Upload;

Upload.Layout = function LayoutPage() {
  return (
    <Layout header={true} sidebar={false}>
      <Upload />
    </Layout>
  );
};
