import React, { Fragment } from 'react';
import Head from 'next/head';

function Tag() {
  return (
    <Fragment>
      <Head>
        <title>Hashtag</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>page tag</div>
    </Fragment>
  );
}

export default Tag;
